### PR TITLE
Add links to headers

### PR DESCRIPTION
**Pull request by hermanschaaf**
I don't know what you guys think about this (or how to test it locally), but I thought it would be nice if the links in the sidebar took you to the relevant header on the page. :cake:

### CODE REVIEW

**Comment by willbarrett** [comment]
Cool - thanks!

**Comment by willbarrett** [comment]
Just tested it out - unfortunately it won't work with our current markdown processor:

selection_091

**Comment by hermanschaaf** [comment]
Ah, that's a shame. It looks like it's taking the HTML from the header and
putting it in the sidebar - I wonder, would it be a workaround to place the
anchor tags right above the headers, instead of inside?

**Comment by willbarrett** [comment]
Might be worth a try!

**Pull request merged**
